<?php
/**
 * marketplace/php/seed.php
 *
 * Populates MySQL database with:
 * - 9 Categories
 * - 14 Provider Nodes
 * - 52 Functional x402 Autonomous Services
 * - Default Users, Orders, Transactions & Reviews
 */

require_once __DIR__ . '/db.php';

$pdo = getDbConnection();

echo "[SEED] Initializing MySQL tables...\n";

// 1. Seed Categories
$stmtCat = $pdo->prepare("INSERT INTO categories (id, name, description) VALUES (:id, :name, :description) ON DUPLICATE KEY UPDATE name = VALUES(name), description = VALUES(description)");
$categories = [
  ['id' => 'translation', 'name' => 'Translation & Localization', 'description' => 'Neural, dialect, legal, and multi-lingual translation'],
  ['id' => 'data-compute', 'name' => 'Compute & Web Intelligence', 'description' => 'HPC distributed compute, scraping, and big data ETL'],
  ['id' => 'vision-ocr', 'name' => 'Vision & OCR Processing', 'description' => 'Document layout analysis, invoice OCR, and object segmentation'],
  ['id' => 'text-generation', 'name' => 'Text Generation & Reasoning', 'description' => 'Foundation LLMs, logic planners, and hierarchical summarizers'],
  ['id' => 'speech-audio', 'name' => 'Speech & Audio AI', 'description' => 'Neural TTS, speech-to-text transcription, and audio diarization'],
  ['id' => 'image-video', 'name' => 'Image & Video Synthesis', 'description' => 'Latent diffusion 4K, video temporal interpolation, and upscaling'],
  ['id' => 'code-dev', 'name' => 'Code & Sandbox Execution', 'description' => 'AST code security auditing, refactoring, and sandbox runners'],
  ['id' => 'rag-embeddings', 'name' => 'RAG & Vector Retrieval', 'description' => '3072-dim embeddings, cross-encoders, and knowledge graphs'],
  ['id' => 'document-research', 'name' => 'Research & Content Safety', 'description' => 'Toxicity moderation, PII redaction, and academic literature extraction'],
];
foreach ($categories as $c) {
    $stmtCat->execute($c);
}
echo "[SEED] Seeded " . count($categories) . " categories.\n";

// 2. Seed Providers
$stmtProv = $pdo->prepare("INSERT INTO providers (id, name, description, service_type, endpoint, rating, quality_score, availability, verified) VALUES (:id, :name, :description, :service_type, :endpoint, :rating, :quality_score, :availability, :verified) ON DUPLICATE KEY UPDATE name = VALUES(name), description = VALUES(description), rating = VALUES(rating), quality_score = VALUES(quality_score)");

$providers = [
  [
    'id' => 'alpha-translate',
    'name' => 'Alpha Translation Labs',
    'description' => '',
    'service_type' => 'translation',
    'endpoint' => '/x402/providers/alpha-translate/service',
    'rating' => 4.74,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'beta-translate',
    'name' => 'Beta FastTranslate Engine',
    'description' => '',
    'service_type' => 'translation',
    'endpoint' => '/x402/providers/beta-translate/service',
    'rating' => 4.74,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'gamma-translate',
    'name' => 'Gamma Enterprise Localization',
    'description' => '',
    'service_type' => 'translation',
    'endpoint' => '/x402/providers/gamma-translate/service',
    'rating' => 4.72,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'delta-compute',
    'name' => 'Delta Distributed Compute',
    'description' => '',
    'service_type' => 'data-compute',
    'endpoint' => '/x402/providers/delta-compute/service',
    'rating' => 4.87,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'epsilon-vision',
    'name' => 'Epsilon Vision & OCR Systems',
    'description' => '',
    'service_type' => 'vision-ocr',
    'endpoint' => '/x402/providers/epsilon-vision/service',
    'rating' => 4.61,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'zeta-llm',
    'name' => 'Zeta Foundation Models',
    'description' => '',
    'service_type' => 'text-generation',
    'endpoint' => '/x402/providers/zeta-llm/service',
    'rating' => 4.95,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'eta-summarize',
    'name' => 'Eta Synthesis & Summarization',
    'description' => '',
    'service_type' => 'text-generation',
    'endpoint' => '/x402/providers/eta-summarize/service',
    'rating' => 4.76,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'theta-audio',
    'name' => 'Theta Voice & Speech AI',
    'description' => '',
    'service_type' => 'speech-audio',
    'endpoint' => '/x402/providers/theta-audio/service',
    'rating' => 4.83,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'iota-diffusion',
    'name' => 'Iota Media & Diffusion Labs',
    'description' => '',
    'service_type' => 'image-video',
    'endpoint' => '/x402/providers/iota-diffusion/service',
    'rating' => 4.83,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'kappa-data',
    'name' => 'Kappa Web Intelligence & ETL',
    'description' => '',
    'service_type' => 'data-compute',
    'endpoint' => '/x402/providers/kappa-data/service',
    'rating' => 4.94,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'lambda-code',
    'name' => 'Lambda Code & Execution Sandbox',
    'description' => '',
    'service_type' => 'code-dev',
    'endpoint' => '/x402/providers/lambda-code/service',
    'rating' => 4.64,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'mu-embeddings',
    'name' => 'Mu Vector & Embeddings Mesh',
    'description' => '',
    'service_type' => 'rag-embeddings',
    'endpoint' => '/x402/providers/mu-embeddings/service',
    'rating' => 4.85,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'nu-rag',
    'name' => 'Nu RAG & Knowledge Graph Engine',
    'description' => '',
    'service_type' => 'rag-embeddings',
    'endpoint' => '/x402/providers/nu-rag/service',
    'rating' => 4.77,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
  [
    'id' => 'xi-compliance',
    'name' => 'Xi Moderation & Research Guardrails',
    'description' => '',
    'service_type' => 'document-research',
    'endpoint' => '/x402/providers/xi-compliance/service',
    'rating' => 4.95,
    'quality_score' => 0.94,
    'availability' => 1,
    'verified' => 1,
  ],
];
foreach ($providers as $p) {
    $stmtProv->execute($p);
}
echo "[SEED] Seeded " . count($providers) . " providers.\n";

// 3. Seed Services
$stmtSvc = $pdo->prepare("INSERT INTO services (id, provider_id, category_id, name, description, price, price_unit, delivery_time, latency_ms, quality_score, availability, status, endpoint, x402_enabled) VALUES (:id, :provider_id, :category_id, :name, :description, :price, :price_unit, :delivery_time, :latency_ms, :quality_score, :availability, :status, :endpoint, :x402_enabled) ON DUPLICATE KEY UPDATE name = VALUES(name), description = VALUES(description), price = VALUES(price), quality_score = VALUES(quality_score)");

$services = [
  [
    'id' => 'text-translate',
    'provider_id' => 'alpha-translate',
    'category_id' => 'translation',
    'name' => 'Neural Text Translation',
    'description' => 'Accurate multi-language translation with cultural nuance verification.',
    'price' => 4,
    'price_unit' => 'request',
    'delivery_time' => '195ms',
    'latency_ms' => 195,
    'quality_score' => 0.92,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/alpha-translate/service?serviceId=text-translate',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'legal-translate',
    'provider_id' => 'alpha-translate',
    'category_id' => 'translation',
    'name' => 'Certified Legal & Financial Translation',
    'description' => 'High-compliance sworn translation for contracts, terms, and cross-border filings.',
    'price' => 5,
    'price_unit' => 'request',
    'delivery_time' => '320ms',
    'latency_ms' => 320,
    'quality_score' => 0.96,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/alpha-translate/service?serviceId=legal-translate',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'dialect-localize',
    'provider_id' => 'alpha-translate',
    'category_id' => 'translation',
    'name' => 'Dialect & Cultural Localization',
    'description' => 'Colloquial and regional dialect adaptation preserving brand voice.',
    'price' => 3.5,
    'price_unit' => 'request',
    'delivery_time' => '180ms',
    'latency_ms' => 180,
    'quality_score' => 0.9,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/alpha-translate/service?serviceId=dialect-localize',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'bilingual-align',
    'provider_id' => 'alpha-translate',
    'category_id' => 'translation',
    'name' => 'Bilingual Sentence & Corpus Alignment',
    'description' => 'Bi-text parallel sentence segmentation and automated translation memory generation.',
    'price' => 2.5,
    'price_unit' => 'request',
    'delivery_time' => '140ms',
    'latency_ms' => 140,
    'quality_score' => 0.89,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/alpha-translate/service?serviceId=bilingual-align',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'budget-translate',
    'provider_id' => 'beta-translate',
    'category_id' => 'translation',
    'name' => 'High-Throughput Bulk Translation',
    'description' => 'Ultra-fast, cost-effective machine translation optimized for high volume streams.',
    'price' => 2,
    'price_unit' => 'request',
    'delivery_time' => '90ms',
    'latency_ms' => 90,
    'quality_score' => 0.83,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/beta-translate/service?serviceId=budget-translate',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'glossary-translate',
    'provider_id' => 'beta-translate',
    'category_id' => 'translation',
    'name' => 'Terminology-Constrained Translation',
    'description' => 'Enforces strict custom entity mappings and terminology glossaries.',
    'price' => 2.5,
    'price_unit' => 'request',
    'delivery_time' => '110ms',
    'latency_ms' => 110,
    'quality_score' => 0.86,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/beta-translate/service?serviceId=glossary-translate',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'streaming-translate',
    'provider_id' => 'beta-translate',
    'category_id' => 'translation',
    'name' => 'Real-Time Low-Latency Translation',
    'description' => 'Sub-100ms chunked token translation for real-time live captions and voice bots.',
    'price' => 3,
    'price_unit' => 'request',
    'delivery_time' => '80ms',
    'latency_ms' => 80,
    'quality_score' => 0.85,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/beta-translate/service?serviceId=streaming-translate',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'expert-translate',
    'provider_id' => 'gamma-translate',
    'category_id' => 'translation',
    'name' => 'Expert Human-in-the-Loop Translation',
    'description' => 'Double-blind reviewed enterprise translation with 98% linguistic guarantee.',
    'price' => 7,
    'price_unit' => 'request',
    'delivery_time' => '450ms',
    'latency_ms' => 450,
    'quality_score' => 0.98,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/gamma-translate/service?serviceId=expert-translate',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'patents-translate',
    'provider_id' => 'gamma-translate',
    'category_id' => 'translation',
    'name' => 'Multilingual Patent & IP Translation',
    'description' => 'WIPO / PCT compliant patent claim translation with technical fidelity.',
    'price' => 6.5,
    'price_unit' => 'request',
    'delivery_time' => '400ms',
    'latency_ms' => 400,
    'quality_score' => 0.97,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/gamma-translate/service?serviceId=patents-translate',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'medical-translate',
    'provider_id' => 'gamma-translate',
    'category_id' => 'translation',
    'name' => 'Clinical & Medical Protocol Translation',
    'description' => 'FDA / EMA trial protocol translations with MeSH and SNOMED vocabulary checking.',
    'price' => 6,
    'price_unit' => 'request',
    'delivery_time' => '380ms',
    'latency_ms' => 380,
    'quality_score' => 0.97,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/gamma-translate/service?serviceId=medical-translate',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'data-process',
    'provider_id' => 'delta-compute',
    'category_id' => 'data-compute',
    'name' => 'Statistical Dataset Aggregation',
    'description' => 'Deterministic statistical summary, moments calculation, and distribution analysis.',
    'price' => 3,
    'price_unit' => 'job',
    'delivery_time' => '140ms',
    'latency_ms' => 140,
    'quality_score' => 0.88,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/delta-compute/service?serviceId=data-process',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'matrix-compute',
    'provider_id' => 'delta-compute',
    'category_id' => 'data-compute',
    'name' => 'High-Performance Matrix Operations',
    'description' => 'BLAS/LAPACK accelerated GPU matrix multiplication and Eigenvalue decomposition.',
    'price' => 4.5,
    'price_unit' => 'job',
    'delivery_time' => '210ms',
    'latency_ms' => 210,
    'quality_score' => 0.93,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/delta-compute/service?serviceId=matrix-compute',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'monte-carlo',
    'provider_id' => 'delta-compute',
    'category_id' => 'data-compute',
    'name' => 'Monte Carlo Risk Simulation',
    'description' => '100,000-path stochastic probability modeling and value-at-risk (VaR) estimation.',
    'price' => 5,
    'price_unit' => 'job',
    'delivery_time' => '290ms',
    'latency_ms' => 290,
    'quality_score' => 0.94,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/delta-compute/service?serviceId=monte-carlo',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'time-series-calc',
    'provider_id' => 'delta-compute',
    'category_id' => 'data-compute',
    'name' => 'Time-Series Anomaly Detection',
    'description' => 'Real-time STL seasonal decomposition and statistical outlier pinpointing.',
    'price' => 3.5,
    'price_unit' => 'job',
    'delivery_time' => '160ms',
    'latency_ms' => 160,
    'quality_score' => 0.9,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/delta-compute/service?serviceId=time-series-calc',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'image-analyze',
    'provider_id' => 'epsilon-vision',
    'category_id' => 'vision-ocr',
    'name' => 'Multimodal Object & Scene Detection',
    'description' => 'Zero-shot visual segment labeling, bounding box regression, and scene categorization.',
    'price' => 4.5,
    'price_unit' => 'request',
    'delivery_time' => '380ms',
    'latency_ms' => 380,
    'quality_score' => 0.94,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/epsilon-vision/service?serviceId=image-analyze',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'ocr-document',
    'provider_id' => 'epsilon-vision',
    'category_id' => 'vision-ocr',
    'name' => 'Multi-Language Document OCR',
    'description' => 'Layout-aware character recognition with font hierarchy and reading-order recovery.',
    'price' => 3.5,
    'price_unit' => 'request',
    'delivery_time' => '250ms',
    'latency_ms' => 250,
    'quality_score' => 0.92,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/epsilon-vision/service?serviceId=ocr-document',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'receipt-invoice-ocr',
    'provider_id' => 'epsilon-vision',
    'category_id' => 'vision-ocr',
    'name' => 'Structured Invoice & Receipt Table Parser',
    'description' => 'Extract line items, tax IDs, invoice dates, and totals into normalized JSON schemas.',
    'price' => 4,
    'price_unit' => 'request',
    'delivery_time' => '290ms',
    'latency_ms' => 290,
    'quality_score' => 0.95,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/epsilon-vision/service?serviceId=receipt-invoice-ocr',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'facial-landmark',
    'provider_id' => 'epsilon-vision',
    'category_id' => 'vision-ocr',
    'name' => 'Biometric Facial Landmark & Pose Detection',
    'description' => '468-point 3D facial mesh geometry and head pose orientation calculation.',
    'price' => 3,
    'price_unit' => 'request',
    'delivery_time' => '200ms',
    'latency_ms' => 200,
    'quality_score' => 0.91,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/epsilon-vision/service?serviceId=facial-landmark',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'deep-reasoning',
    'provider_id' => 'zeta-llm',
    'category_id' => 'text-generation',
    'name' => 'Chain-of-Thought Logical Reasoning',
    'description' => 'Multi-step analytical reasoning and mathematical deduction with step-by-step verification.',
    'price' => 5.5,
    'price_unit' => 'request',
    'delivery_time' => '420ms',
    'latency_ms' => 420,
    'quality_score' => 0.96,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/zeta-llm/service?serviceId=deep-reasoning',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'creative-writing',
    'provider_id' => 'zeta-llm',
    'category_id' => 'text-generation',
    'name' => 'Dynamic Copywriting & Creative Storytelling',
    'description' => 'High-engagement narrative generation, marketing slogans, and technical prose.',
    'price' => 3.5,
    'price_unit' => 'request',
    'delivery_time' => '230ms',
    'latency_ms' => 230,
    'quality_score' => 0.91,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/zeta-llm/service?serviceId=creative-writing',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'agent-planner',
    'provider_id' => 'zeta-llm',
    'category_id' => 'text-generation',
    'name' => 'Autonomous Subtask Decomposition & Planning',
    'description' => 'Breaks high-level user goals into structured dependency graphs and execution actions.',
    'price' => 4,
    'price_unit' => 'request',
    'delivery_time' => '280ms',
    'latency_ms' => 280,
    'quality_score' => 0.93,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/zeta-llm/service?serviceId=agent-planner',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'json-structured',
    'provider_id' => 'zeta-llm',
    'category_id' => 'text-generation',
    'name' => 'Strict JSON Schema Extraction',
    'description' => 'Zero-hallucination structured entity parsing strictly validated against JSONSchema.',
    'price' => 3,
    'price_unit' => 'request',
    'delivery_time' => '180ms',
    'latency_ms' => 180,
    'quality_score' => 0.94,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/zeta-llm/service?serviceId=json-structured',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'tldr-summary',
    'provider_id' => 'eta-summarize',
    'category_id' => 'text-generation',
    'name' => 'Executive Briefing & Key Takeaway Generator',
    'description' => 'Distills complex technical documentation into 3 concise executive bullet points.',
    'price' => 2.5,
    'price_unit' => 'request',
    'delivery_time' => '150ms',
    'latency_ms' => 150,
    'quality_score' => 0.91,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/eta-summarize/service?serviceId=tldr-summary',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'longdoc-distill',
    'provider_id' => 'eta-summarize',
    'category_id' => 'text-generation',
    'name' => '100+ Page Recursive Document Distiller',
    'description' => 'Recursive hierarchical map-reduce summarization for technical whitepapers and books.',
    'price' => 5,
    'price_unit' => 'request',
    'delivery_time' => '360ms',
    'latency_ms' => 360,
    'quality_score' => 0.95,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/eta-summarize/service?serviceId=longdoc-distill',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'meeting-action-items',
    'provider_id' => 'eta-summarize',
    'category_id' => 'text-generation',
    'name' => 'Multi-Speaker Meeting Action Item Extractor',
    'description' => 'Identifies deliverables, assignees, deadlines, and unassigned commitments from transcripts.',
    'price' => 3.5,
    'price_unit' => 'request',
    'delivery_time' => '210ms',
    'latency_ms' => 210,
    'quality_score' => 0.92,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/eta-summarize/service?serviceId=meeting-action-items',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'whisper-stt',
    'provider_id' => 'theta-audio',
    'category_id' => 'speech-audio',
    'name' => 'Whisper Multilingual Speech-to-Text',
    'description' => 'High-accuracy audio transcription with word-level timestamps and punctuation.',
    'price' => 3.5,
    'price_unit' => 'request',
    'delivery_time' => '240ms',
    'latency_ms' => 240,
    'quality_score' => 0.94,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/theta-audio/service?serviceId=whisper-stt',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'neural-tts',
    'provider_id' => 'theta-audio',
    'category_id' => 'speech-audio',
    'name' => 'Expressive Neural Voice Synthesis (TTS)',
    'description' => 'Natural prosody neural speech generator supporting 40+ lifelike speaker voices.',
    'price' => 3,
    'price_unit' => 'request',
    'delivery_time' => '190ms',
    'latency_ms' => 190,
    'quality_score' => 0.92,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/theta-audio/service?serviceId=neural-tts',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'audio-diarization',
    'provider_id' => 'theta-audio',
    'category_id' => 'speech-audio',
    'name' => 'Multi-Speaker Audio Separation & Diarization',
    'description' => 'Distinguishes distinct voices and annotates timestamps per individual speaker.',
    'price' => 4,
    'price_unit' => 'request',
    'delivery_time' => '290ms',
    'latency_ms' => 290,
    'quality_score' => 0.93,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/theta-audio/service?serviceId=audio-diarization',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'audio-noise-filter',
    'provider_id' => 'theta-audio',
    'category_id' => 'speech-audio',
    'name' => 'Neural Audio Noise Reduction & Clean-up',
    'description' => 'Removes background room reverberation, HVAC hum, and street noise from audio feeds.',
    'price' => 2.5,
    'price_unit' => 'request',
    'delivery_time' => '160ms',
    'latency_ms' => 160,
    'quality_score' => 0.89,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/theta-audio/service?serviceId=audio-noise-filter',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'text-to-image',
    'provider_id' => 'iota-diffusion',
    'category_id' => 'image-video',
    'name' => '4K Photorealistic Diffusion Generation',
    'description' => 'State-of-the-art latent diffusion synthesis with precise prompt adherence.',
    'price' => 6,
    'price_unit' => 'request',
    'delivery_time' => '520ms',
    'latency_ms' => 520,
    'quality_score' => 0.95,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/iota-diffusion/service?serviceId=text-to-image',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'image-upscaler',
    'provider_id' => 'iota-diffusion',
    'category_id' => 'image-video',
    'name' => '4x Super-Resolution Neural Upscaling',
    'description' => 'Restores textures, sharpens edges, and removes compression artifacts at 4x factor.',
    'price' => 2.5,
    'price_unit' => 'request',
    'delivery_time' => '210ms',
    'latency_ms' => 210,
    'quality_score' => 0.93,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/iota-diffusion/service?serviceId=image-upscaler',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'video-frame-tagger',
    'provider_id' => 'iota-diffusion',
    'category_id' => 'image-video',
    'name' => 'Keyframe Extraction & Video Action Tagging',
    'description' => 'Temporal scene boundary detection and semantic activity labeling in video clips.',
    'price' => 5,
    'price_unit' => 'request',
    'delivery_time' => '460ms',
    'latency_ms' => 460,
    'quality_score' => 0.91,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/iota-diffusion/service?serviceId=video-frame-tagger',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'background-remover',
    'provider_id' => 'iota-diffusion',
    'category_id' => 'image-video',
    'name' => 'Instant Object Masking & Alpha Matting',
    'description' => 'Sub-pixel alpha matte foreground segmentation with clean hair and translucent edges.',
    'price' => 2,
    'price_unit' => 'request',
    'delivery_time' => '140ms',
    'latency_ms' => 140,
    'quality_score' => 0.94,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/iota-diffusion/service?serviceId=background-remover',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'web-scraper',
    'provider_id' => 'kappa-data',
    'category_id' => 'data-compute',
    'name' => 'Headless Anti-Bot Web Data Extraction',
    'description' => 'Bypasses bot protections, renders client-side SPAs, and returns DOM snapshots.',
    'price' => 3,
    'price_unit' => 'job',
    'delivery_time' => '220ms',
    'latency_ms' => 220,
    'quality_score' => 0.9,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/kappa-data/service?serviceId=web-scraper',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'html-to-markdown',
    'provider_id' => 'kappa-data',
    'category_id' => 'data-compute',
    'name' => 'Clean Web Article & Table Markdown Parser',
    'description' => 'Strips ads, boilerplate navigation, and converts clean editorial content to Markdown.',
    'price' => 1.5,
    'price_unit' => 'job',
    'delivery_time' => '100ms',
    'latency_ms' => 100,
    'quality_score' => 0.92,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/kappa-data/service?serviceId=html-to-markdown',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'schema-enrichment',
    'provider_id' => 'kappa-data',
    'category_id' => 'data-compute',
    'name' => 'Lead & Entity Graph Enrichment',
    'description' => 'Enriches corporate domains with firmographic metadata, technology stacks, and social IDs.',
    'price' => 4,
    'price_unit' => 'job',
    'delivery_time' => '270ms',
    'latency_ms' => 270,
    'quality_score' => 0.91,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/kappa-data/service?serviceId=schema-enrichment',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'proxy-rotator',
    'provider_id' => 'kappa-data',
    'category_id' => 'data-compute',
    'name' => 'Geotargeted Residential Request Tunnel',
    'description' => 'Rotates residential IPs across 190 countries with 99.9% uptime and zero throttling.',
    'price' => 2.5,
    'price_unit' => 'job',
    'delivery_time' => '180ms',
    'latency_ms' => 180,
    'quality_score' => 0.94,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/kappa-data/service?serviceId=proxy-rotator',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'code-audit',
    'provider_id' => 'lambda-code',
    'category_id' => 'code-dev',
    'name' => 'Automated AST Security & Vulnerability Auditor',
    'description' => 'Static abstract syntax tree inspection for reentrancy, injection, and overflow bugs.',
    'price' => 4.5,
    'price_unit' => 'job',
    'delivery_time' => '310ms',
    'latency_ms' => 310,
    'quality_score' => 0.95,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/lambda-code/service?serviceId=code-audit',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'isolated-eval',
    'provider_id' => 'lambda-code',
    'category_id' => 'code-dev',
    'name' => 'Sandboxed Python/Node.js Code Execution',
    'description' => 'gVisor microVM isolated execution with strict memory and CPU quotas.',
    'price' => 3,
    'price_unit' => 'job',
    'delivery_time' => '190ms',
    'latency_ms' => 190,
    'quality_score' => 0.97,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/lambda-code/service?serviceId=isolated-eval',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'sql-optimizer',
    'provider_id' => 'lambda-code',
    'category_id' => 'code-dev',
    'name' => 'SQL Query Analysis & Index Recommendation',
    'description' => 'EXPLAIN plan cost reduction and compound index synthesis for PostgreSQL/MySQL.',
    'price' => 3.5,
    'price_unit' => 'job',
    'delivery_time' => '210ms',
    'latency_ms' => 210,
    'quality_score' => 0.92,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/lambda-code/service?serviceId=sql-optimizer',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'api-mock-gen',
    'provider_id' => 'lambda-code',
    'category_id' => 'code-dev',
    'name' => 'OpenAPI/Swagger Contract to Mock Generator',
    'description' => 'Generates realistic dynamic mock endpoints with faker data from OpenAPI specifications.',
    'price' => 2.5,
    'price_unit' => 'job',
    'delivery_time' => '150ms',
    'latency_ms' => 150,
    'quality_score' => 0.9,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/lambda-code/service?serviceId=api-mock-gen',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'vector-embed-3072',
    'provider_id' => 'mu-embeddings',
    'category_id' => 'rag-embeddings',
    'name' => 'Dense 3072-dim Text Vector Embedding',
    'description' => 'MTEB leaderboard-topping dense vector embeddings for semantic retrieval.',
    'price' => 2,
    'price_unit' => 'request',
    'delivery_time' => '95ms',
    'latency_ms' => 95,
    'quality_score' => 0.96,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/mu-embeddings/service?serviceId=vector-embed-3072',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'cross-encoder-rerank',
    'provider_id' => 'mu-embeddings',
    'category_id' => 'rag-embeddings',
    'name' => 'Semantic Cross-Encoder Passage Reranker',
    'description' => 'Deep attention reranking of top-50 candidate documents with relevance scoring.',
    'price' => 3,
    'price_unit' => 'request',
    'delivery_time' => '170ms',
    'latency_ms' => 170,
    'quality_score' => 0.95,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/mu-embeddings/service?serviceId=cross-encoder-rerank',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'clustering-similarity',
    'provider_id' => 'mu-embeddings',
    'category_id' => 'rag-embeddings',
    'name' => 'Multi-Vector Cosine Similarity & Clustering',
    'description' => 'HDBSCAN vector clustering and nearest-neighbor graph construction.',
    'price' => 2.5,
    'price_unit' => 'request',
    'delivery_time' => '140ms',
    'latency_ms' => 140,
    'quality_score' => 0.91,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/mu-embeddings/service?serviceId=clustering-similarity',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'rag-search',
    'provider_id' => 'nu-rag',
    'category_id' => 'rag-embeddings',
    'name' => 'Hybrid Vector + BM25 Context Retriever',
    'description' => 'Reciprocal Rank Fusion across dense embeddings and sparse keyword indexes.',
    'price' => 4,
    'price_unit' => 'request',
    'delivery_time' => '260ms',
    'latency_ms' => 260,
    'quality_score' => 0.94,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/nu-rag/service?serviceId=rag-search',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'knowledge-graph',
    'provider_id' => 'nu-rag',
    'category_id' => 'rag-embeddings',
    'name' => 'Unstructured Text to Entity-Relationship Graph',
    'description' => 'Extracts nodes, edges, and triples into Neo4j/Cypher compatible graph structures.',
    'price' => 5.5,
    'price_unit' => 'request',
    'delivery_time' => '390ms',
    'latency_ms' => 390,
    'quality_score' => 0.93,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/nu-rag/service?serviceId=knowledge-graph',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'document-chunker',
    'provider_id' => 'nu-rag',
    'category_id' => 'rag-embeddings',
    'name' => 'Semantic Chunking with Overlap Optimization',
    'description' => 'Boundary-respecting semantic text splitter maintaining coherent contextual units.',
    'price' => 2,
    'price_unit' => 'request',
    'delivery_time' => '120ms',
    'latency_ms' => 120,
    'quality_score' => 0.9,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/nu-rag/service?serviceId=document-chunker',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'citation-verifier',
    'provider_id' => 'nu-rag',
    'category_id' => 'rag-embeddings',
    'name' => 'Source Document Grounding & Citation Verifier',
    'description' => 'Verifies every sentence in generative output against grounding source documents.',
    'price' => 3.5,
    'price_unit' => 'request',
    'delivery_time' => '210ms',
    'latency_ms' => 210,
    'quality_score' => 0.96,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/nu-rag/service?serviceId=citation-verifier',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'content-moderator',
    'provider_id' => 'xi-compliance',
    'category_id' => 'document-research',
    'name' => 'Multilingual Toxic & Harm Content Classifier',
    'description' => 'Multi-category safety evaluation covering hate speech, harassment, and security threats.',
    'price' => 2,
    'price_unit' => 'request',
    'delivery_time' => '110ms',
    'latency_ms' => 110,
    'quality_score' => 0.95,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/xi-compliance/service?serviceId=content-moderator',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'pii-redactor',
    'provider_id' => 'xi-compliance',
    'category_id' => 'document-research',
    'name' => 'Automated GDPR/HIPAA Personal Data Redactor',
    'description' => 'Named entity recognition masking emails, phone numbers, SSNs, and crypto private keys.',
    'price' => 3,
    'price_unit' => 'request',
    'delivery_time' => '170ms',
    'latency_ms' => 170,
    'quality_score' => 0.96,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/xi-compliance/service?serviceId=pii-redactor',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'academic-search',
    'provider_id' => 'xi-compliance',
    'category_id' => 'document-research',
    'name' => 'Semantic Scholar & ArXiv Research Retrieval',
    'description' => 'Automated literature review extracting peer-reviewed abstracts and citation graphs.',
    'price' => 3.5,
    'price_unit' => 'request',
    'delivery_time' => '240ms',
    'latency_ms' => 240,
    'quality_score' => 0.92,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/xi-compliance/service?serviceId=academic-search',
    'x402_enabled' => 1,
  ],
  [
    'id' => 'sentiment-analyzer',
    'provider_id' => 'xi-compliance',
    'category_id' => 'document-research',
    'name' => 'Granular Aspect-Based Sentiment Classifier',
    'description' => 'Measures polarity, subjective tone, and emotional valence across text corpora.',
    'price' => 2,
    'price_unit' => 'request',
    'delivery_time' => '130ms',
    'latency_ms' => 130,
    'quality_score' => 0.89,
    'availability' => 1,
    'status' => 'AVAILABLE',
    'endpoint' => '/x402/providers/xi-compliance/service?serviceId=sentiment-analyzer',
    'x402_enabled' => 1,
  ],
];
foreach ($services as $s) {
    $stmtSvc->execute($s);
}
echo "[SEED] Seeded " . count($services) . " services.\n";

// 4. Seed Default Agent User
$stmtUser = $pdo->prepare("INSERT INTO users (id, name, email, wallet_address, role) VALUES (:id, :name, :email, :wallet_address, :role) ON DUPLICATE KEY UPDATE name = VALUES(name)");
$stmtUser->execute([
    'id' => 'user_agent_w3a1',
    'name' => 'W3A-1 Autonomous Agent Signer',
    'email' => 'agent@w3a1.network',
    'wallet_address' => '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
    'role' => 'agent',
]);

// 5. Seed Initial Orders and Transactions
$stmtOrder = $pdo->prepare("INSERT INTO orders (id, user_id, service_id, provider_id, amount, status, payload_input, payload_output, delivery_hash) VALUES (:id, :user_id, :service_id, :provider_id, :amount, :status, :payload_input, :payload_output, :delivery_hash) ON DUPLICATE KEY UPDATE status = VALUES(status)");
$stmtTx = $pdo->prepare("INSERT INTO transactions (id, order_id, transaction_reference, amount, status, risk_score, block_number, network, chain_id, etherscan_url) VALUES (:id, :order_id, :transaction_reference, :amount, :status, :risk_score, :block_number, :network, :chain_id, :etherscan_url) ON DUPLICATE KEY UPDATE status = VALUES(status)");

$seedOrders = [
    [
        'order' => [
            'id' => 'ord_sepolia_11766134',
            'user_id' => 'user_agent_w3a1',
            'service_id' => 'text-translate',
            'provider_id' => 'alpha-translate',
            'amount' => 4.00,
            'status' => 'SETTLED',
            'payload_input' => 'Autonomous PDF Legal Agreement Translation into Spanish',
            'payload_output' => 'Este Acuerdo legal se celebra y entra en vigencia con plena validez juridica...',
            'delivery_hash' => '0x6f3e1b092df48641a9985923b7e411c50064f2ab72e424e8e040c5b367098412',
        ],
        'tx' => [
            'id' => 'tx_sepolia_11766134',
            'order_id' => 'ord_sepolia_11766134',
            'transaction_reference' => '0x20c9008318891465b63dd8720c78919b3e582a09af77d77336dd97d448d3a136',
            'amount' => 4.00,
            'status' => 'SETTLED',
            'risk_score' => 0.02,
            'block_number' => 11766134,
            'network' => 'Ethereum Sepolia Testnet',
            'chain_id' => 11155111,
            'etherscan_url' => 'https://sepolia.etherscan.io/tx/0x20c9008318891465b63dd8720c78919b3e582a09af77d77336dd97d448d3a136',
        ]
    ],
    [
        'order' => [
            'id' => 'ord_sepolia_11766123',
            'user_id' => 'user_agent_w3a1',
            'service_id' => 'legal-translate',
            'provider_id' => 'alpha-translate',
            'amount' => 5.00,
            'status' => 'SETTLED',
            'payload_input' => 'Cross-Border Multi-Party Sworn Contract Validation',
            'payload_output' => 'Certified sworn translation verified under x402 V2 protocol.',
            'delivery_hash' => '0x9d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e',
        ],
        'tx' => [
            'id' => 'tx_sepolia_11766123',
            'order_id' => 'ord_sepolia_11766123',
            'transaction_reference' => '0xa7a187321a0f29247cc0dba54479ba21de438c9142c1c1f750c77e5ad32c1e16',
            'amount' => 5.00,
            'status' => 'SETTLED',
            'risk_score' => 0.04,
            'block_number' => 11766123,
            'network' => 'Ethereum Sepolia Testnet',
            'chain_id' => 11155111,
            'etherscan_url' => 'https://sepolia.etherscan.io/tx/0xa7a187321a0f29247cc0dba54479ba21de438c9142c1c1f750c77e5ad32c1e16',
        ]
    ]
];

foreach ($seedOrders as $so) {
    $stmtOrder->execute($so['order']);
    $stmtTx->execute($so['tx']);
}

// 6. Seed Sample Review
$stmtRev = $pdo->prepare("INSERT INTO reviews (id, order_id, user_id, provider_id, rating, comment) VALUES (:id, :order_id, :user_id, :provider_id, :rating, :comment) ON DUPLICATE KEY UPDATE rating = VALUES(rating)");
$stmtRev->execute([
    'id' => 'rev_001',
    'order_id' => 'ord_sepolia_11766134',
    'user_id' => 'user_agent_w3a1',
    'provider_id' => 'alpha-translate',
    'rating' => 5.0,
    'comment' => 'Flawless autonomous delivery with cryptographic proof matching on Sepolia.',
]);

echo "[SEED] Seeded default user, orders, transactions, and reviews.\n";
echo "=== MySQL SEEDING COMPLETE: w3a1_marketplace ready ===\n";
