"use strict";

const API_BACKED_SERVICES = [
  {
    service_id: "ipstack-lookup",
    service_name: "IP Location Intelligence",
    provider_id: "ipstack-geo",
    provider_name: "IPStack Geolocation",
    category_id: "data-compute",
    category_name: "Compute & Web Intelligence",
    description: "Real-time IPv4/IPv6 geolocation, continent/country lookup, carrier identification, and timezone coordinates.",
    endpoint: "/x402/providers/ipstack-geo/service",
    http_method: "GET",
    authentication_type: "QUERY_PARAM",
    pricing_model: "PER_REQUEST",
    price: 1.50,
    price_unit: "USDC / request",
    currency: "USDC",
    delivery_time: "120ms",
    latency_ms: 120,
    quality_score: 0.95,
    availability: 1,
    status: "AVAILABLE",
    adapter_type: "REST",
    is_api_backed: 1,
    env_key_name: "IPSTACK_API_KEY",
    documentation_url: "https://ipstack.com/documentation",
    terms_url: "https://ipstack.com/terms",
    source_url: "https://ipstack.com",
    request_schema: {
      type: "object",
      properties: {
        ip: { type: "string", description: "Target IPv4 or IPv6 address" },
      },
    },
    response_schema: {
      type: "object",
      properties: {
        ip: { type: "string" },
        country_name: { type: "string" },
        city: { type: "string" },
        latitude: { type: "number" },
        longitude: { type: "number" },
      },
    },
  },
  {
    service_id: "currencylayer-live",
    service_name: "Real-Time Forex & FX Rates",
    provider_id: "currencylayer-fx",
    provider_name: "CurrencyLayer FX",
    category_id: "data-compute",
    category_name: "Compute & Web Intelligence",
    description: "Live real-time foreign exchange rates for 168 world currencies with sub-minute institutional quotes.",
    endpoint: "/x402/providers/currencylayer-fx/service",
    http_method: "GET",
    authentication_type: "QUERY_PARAM",
    pricing_model: "PER_REQUEST",
    price: 1.00,
    price_unit: "USDC / request",
    currency: "USDC",
    delivery_time: "95ms",
    latency_ms: 95,
    quality_score: 0.96,
    availability: 1,
    status: "AVAILABLE",
    adapter_type: "REST",
    is_api_backed: 1,
    env_key_name: "CURRENCY_LAYER_API_KEY",
    documentation_url: "https://currencylayer.com/documentation",
    terms_url: "https://currencylayer.com/terms",
    source_url: "https://currencylayer.com",
    request_schema: {
      type: "object",
      properties: {
        currencies: { type: "string", description: "Comma-separated currency codes (EUR,GBP,JPY,INR)" },
        source: { type: "string", default: "USD" },
      },
    },
    response_schema: {
      type: "object",
      properties: {
        success: { type: "boolean" },
        timestamp: { type: "number" },
        quotes: { type: "object" },
      },
    },
  },
  {
    service_id: "giphy-search",
    service_name: "Giphy Animated Media & Search",
    provider_id: "giphy-media",
    provider_name: "Giphy Media Engine",
    category_id: "image-video",
    category_name: "Image & Video Synthesis",
    description: "Contextual GIF search, meme extraction, and animated visual assets powered by Giphy's knowledge engine.",
    endpoint: "/x402/providers/giphy-media/service",
    http_method: "GET",
    authentication_type: "QUERY_PARAM",
    pricing_model: "PER_REQUEST",
    price: 0.80,
    price_unit: "USDC / request",
    currency: "USDC",
    delivery_time: "150ms",
    latency_ms: 150,
    quality_score: 0.92,
    availability: 1,
    status: "AVAILABLE",
    adapter_type: "REST",
    is_api_backed: 1,
    env_key_name: "GIPHY_API_KEY",
    documentation_url: "https://developers.giphy.com/docs/api/endpoint",
    terms_url: "https://support.giphy.com/hc/en-us/articles/360020027752-GIPHY-User-Terms-of-Service",
    source_url: "https://giphy.com",
    request_schema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Search terms or sentiment prompt" },
        limit: { type: "integer", default: 5 },
      },
    },
    response_schema: {
      type: "object",
      properties: {
        data: { type: "array" },
      },
    },
  },
  {
    service_id: "apiflash-capture",
    service_name: "Automated Web Capture & Snapshot",
    provider_id: "apiflash-render",
    provider_name: "ApiFlash Chrome Cloud",
    category_id: "vision-ocr",
    category_name: "Vision & OCR Processing",
    description: "Headless Chromium high-DPI full-page website screenshots with JavaScript execution and ad-blocking.",
    endpoint: "/x402/providers/apiflash-render/service",
    http_method: "GET",
    authentication_type: "QUERY_PARAM",
    pricing_model: "PER_REQUEST",
    price: 2.00,
    price_unit: "USDC / request",
    currency: "USDC",
    delivery_time: "480ms",
    latency_ms: 480,
    quality_score: 0.94,
    availability: 1,
    status: "AVAILABLE",
    adapter_type: "REST",
    is_api_backed: 1,
    env_key_name: "APIFLASH_ACCESS_KEY",
    documentation_url: "https://apiflash.com/documentation",
    terms_url: "https://apiflash.com/terms",
    source_url: "https://apiflash.com",
    request_schema: {
      type: "object",
      properties: {
        targetUrl: { type: "string", description: "Target website URL to snapshot" },
      },
    },
    response_schema: {
      type: "object",
      properties: {
        url: { type: "string" },
      },
    },
  },
  {
    service_id: "amazon-product-data",
    service_name: "Amazon E-Commerce Scraper",
    provider_id: "amazon-scraper",
    provider_name: "Amazon Web Intelligence",
    category_id: "data-compute",
    category_name: "Compute & Web Intelligence",
    description: "Structured Amazon product catalog extraction: pricing, buy-box owner, rating, reviews count, and stock availability.",
    endpoint: "/x402/providers/amazon-scraper/service",
    http_method: "GET",
    authentication_type: "QUERY_PARAM",
    pricing_model: "PER_REQUEST",
    price: 2.50,
    price_unit: "USDC / request",
    currency: "USDC",
    delivery_time: "350ms",
    latency_ms: 350,
    quality_score: 0.93,
    availability: 1,
    status: "AVAILABLE",
    adapter_type: "REST",
    is_api_backed: 1,
    env_key_name: "AMAZON_SCRAPER_API_KEY",
    documentation_url: "https://amazonscraperapi.com",
    terms_url: "https://amazonscraperapi.com/terms",
    source_url: "https://amazonscraperapi.com",
    request_schema: {
      type: "object",
      properties: {
        asin: { type: "string", description: "Amazon Standard Identification Number (e.g. B08N5WRWNW)" },
      },
    },
    response_schema: {
      type: "object",
      properties: {
        title: { type: "string" },
        price: { type: "string" },
        rating: { type: "number" },
      },
    },
  },
  {
    service_id: "blitapp-snapshot",
    service_name: "Blitapp Cloud Visual Monitor",
    provider_id: "blitapp-cloud",
    provider_name: "Blitapp Automated Snapshots",
    category_id: "vision-ocr",
    category_name: "Vision & OCR Processing",
    description: "Automated recurring visual snapshots with CDN delivery, viewport customization, and visual diff detection.",
    endpoint: "/x402/providers/blitapp-cloud/service",
    http_method: "POST",
    authentication_type: "BEARER_TOKEN",
    pricing_model: "PER_REQUEST",
    price: 2.20,
    price_unit: "USDC / request",
    currency: "USDC",
    delivery_time: "410ms",
    latency_ms: 410,
    quality_score: 0.91,
    availability: 1,
    status: "AVAILABLE",
    adapter_type: "REST",
    is_api_backed: 1,
    env_key_name: "BLITAPP_API_KEY",
    documentation_url: "https://blitapp.com/docs",
    terms_url: "https://blitapp.com/terms",
    source_url: "https://blitapp.com",
    request_schema: {
      type: "object",
      properties: {
        targetUrl: { type: "string" },
        viewport: { type: "string", default: "1440x900" },
      },
    },
    response_schema: {
      type: "object",
      properties: {
        capture_id: { type: "string" },
        image_url: { type: "string" },
      },
    },
  },
  {
    service_id: "apitemplate-pdf",
    service_name: "APITemplate Document Generation",
    provider_id: "apitemplate-docs",
    provider_name: "APITemplate PDF Engine",
    category_id: "document-research",
    category_name: "Research & Content Safety",
    description: "Dynamic enterprise PDF and image generation from reusable templates, JSON schemas, and HTML/CSS canvas.",
    endpoint: "/x402/providers/apitemplate-docs/service",
    http_method: "POST",
    authentication_type: "HEADER",
    pricing_model: "PER_REQUEST",
    price: 3.00,
    price_unit: "USDC / request",
    currency: "USDC",
    delivery_time: "320ms",
    latency_ms: 320,
    quality_score: 0.95,
    availability: 1,
    status: "AVAILABLE",
    adapter_type: "REST",
    is_api_backed: 1,
    env_key_name: "APITEMPLATE_API_KEY",
    documentation_url: "https://apitemplate.io/docs",
    terms_url: "https://apitemplate.io/terms",
    source_url: "https://apitemplate.io",
    request_schema: {
      type: "object",
      properties: {
        templateId: { type: "string" },
        title: { type: "string" },
      },
    },
    response_schema: {
      type: "object",
      properties: {
        download_url: { type: "string" },
        status: { type: "string" },
      },
    },
  },
  {
    service_id: "open-meteo-weather",
    service_name: "Open-Meteo Global Weather",
    provider_id: "open-meteo",
    provider_name: "Open-Meteo Weather API",
    category_id: "data-compute",
    category_name: "Compute & Web Intelligence",
    description: "High-resolution meteorological forecast, real-time temperature, wind speed, and atmospheric conditions worldwide.",
    endpoint: "/x402/providers/open-meteo/service",
    http_method: "GET",
    authentication_type: "NONE",
    pricing_model: "PER_REQUEST",
    price: 0.50,
    price_unit: "USDC / request",
    currency: "USDC",
    delivery_time: "80ms",
    latency_ms: 80,
    quality_score: 0.97,
    availability: 1,
    status: "AVAILABLE",
    adapter_type: "REST",
    is_api_backed: 1,
    env_key_name: null,
    documentation_url: "https://open-meteo.com/en/docs",
    terms_url: "https://open-meteo.com/en/terms",
    source_url: "https://open-meteo.com",
    request_schema: {
      type: "object",
      properties: {
        city: { type: "string", default: "Delhi" },
        latitude: { type: "number" },
        longitude: { type: "number" },
      },
    },
    response_schema: {
      type: "object",
      properties: {
        current_weather: {
          type: "object",
          properties: {
            temperature: { type: "number" },
            windspeed: { type: "number" },
          },
        },
      },
    },
  },
];

const API_BACKED_PROVIDERS = [
  {
    id: "ipstack-geo",
    name: "IPStack Geolocation",
    description: "Global IP address intelligence and coordinate resolution node.",
    service_type: "data-compute",
    endpoint: "/x402/providers/ipstack-geo/service",
    rating: 4.85,
    quality_score: 0.95,
    availability: 1,
    verified: 1,
    wallet_address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  },
  {
    id: "currencylayer-fx",
    name: "CurrencyLayer FX",
    description: "Institutional foreign exchange and algorithmic forex rate oracle.",
    service_type: "data-compute",
    endpoint: "/x402/providers/currencylayer-fx/service",
    rating: 4.90,
    quality_score: 0.96,
    availability: 1,
    verified: 1,
    wallet_address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  },
  {
    id: "giphy-media",
    name: "Giphy Media Engine",
    description: "Global animated short-form visual media and creative content provider.",
    service_type: "image-video",
    endpoint: "/x402/providers/giphy-media/service",
    rating: 4.78,
    quality_score: 0.92,
    availability: 1,
    verified: 1,
    wallet_address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  },
  {
    id: "apiflash-render",
    name: "ApiFlash Chrome Cloud",
    description: "Distributed headless browser website capture and visual document rendering.",
    service_type: "vision-ocr",
    endpoint: "/x402/providers/apiflash-render/service",
    rating: 4.82,
    quality_score: 0.94,
    availability: 1,
    verified: 1,
    wallet_address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  },
  {
    id: "amazon-scraper",
    name: "Amazon Web Intelligence",
    description: "E-commerce product intelligence, price tracking, and catalog indexing node.",
    service_type: "data-compute",
    endpoint: "/x402/providers/amazon-scraper/service",
    rating: 4.80,
    quality_score: 0.93,
    availability: 1,
    verified: 1,
    wallet_address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  },
  {
    id: "blitapp-cloud",
    name: "Blitapp Automated Snapshots",
    description: "Automated recurring visual snapshots with CDN delivery and diff detection.",
    service_type: "vision-ocr",
    endpoint: "/x402/providers/blitapp-cloud/service",
    rating: 4.75,
    quality_score: 0.91,
    availability: 1,
    verified: 1,
    wallet_address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  },
  {
    id: "apitemplate-docs",
    name: "APITemplate PDF Engine",
    description: "Automated PDF and invoice generation from HTML/CSS templates.",
    service_type: "document-research",
    endpoint: "/x402/providers/apitemplate-docs/service",
    rating: 4.88,
    quality_score: 0.95,
    availability: 1,
    verified: 1,
    wallet_address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  },
  {
    id: "open-meteo",
    name: "Open-Meteo Weather API",
    description: "Open-source non-commercial meteorological forecast and weather node.",
    service_type: "data-compute",
    endpoint: "/x402/providers/open-meteo/service",
    rating: 4.92,
    quality_score: 0.97,
    availability: 1,
    verified: 1,
    wallet_address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  },
];

module.exports = {
  API_BACKED_SERVICES,
  API_BACKED_PROVIDERS,
};
