"use strict";

const AuditEvent = Object.freeze({
  // Canonical unified stream events
  INTENT_RECEIVED: "INTENT_RECEIVED",
  PROVIDER_SEARCH: "PROVIDER_SEARCH",
  PROVIDER_SELECTED: "PROVIDER_SELECTED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  PAYMENT_SIGNED: "PAYMENT_SIGNED",
  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",
  SETTLEMENT_SUBMITTED: "SETTLEMENT_SUBMITTED",
  SETTLEMENT_CONFIRMED: "SETTLEMENT_CONFIRMED",
  DELIVERY_RECEIVED: "DELIVERY_RECEIVED",
  HASH_VERIFIED: "HASH_VERIFIED",
  OVERSPEND_BLOCKED: "OVERSPEND_BLOCKED",
  RETRY_DETECTED: "RETRY_DETECTED",
  AGENT_FROZEN: "AGENT_FROZEN",
  AGENT_UNFROZEN: "AGENT_UNFROZEN",
  BUDGET_FUNDED: "BUDGET_FUNDED",
  DELIVERY_TAMPERED: "DELIVERY_TAMPERED",
  SERVICE_PUBLISHED: "SERVICE_PUBLISHED",

  // Legacy/alias events preserved for test backward-compatibility
  REQUESTED: "REQUESTED",
  PAYMENT_AUTHORIZED: "PAYMENT_AUTHORIZED",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  DELIVERED: "DELIVERED",
  VERIFIED: "VERIFIED",
  OVERSPEND_REJECTED: "OVERSPEND_BLOCKED",
  FAILED: "FAILED",
});

module.exports = { AuditEvent };
